trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    checkLatest: true
    versionSpec: '>=12.x'
  displayName: 'Install Node.js'

- script: 'npm install -g markdown-link-check'
  displayName: 'Install markdown-link-check'
    
- powershell: |
    Get-ChildItem -Path "./" -Filter "*.md" -Recurse | ForEach-Object {
      $path = Resolve-Path -Path $_.FullName -Relative
      if(!($path -match "\\\.[^\.\\]+")) {
        markdown-link-check -q $path
      }
    }
  failOnStderr: true
  errorActionPreference: continue
  displayName: 'Check links'
  
